### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by JG-GIT** [PretendoNetwork/juxtaposition#1]
It seems like there isn't a way to do it.

**Comment by ThatNerdyPikachu** [comment]
...Any error messages?

**Comment by superwhiskers** [comment]
if you would like to run this on windows you need to get one of the newer versions of redis to compile on windows first, then run it. then download the cassandra database server and run it. once you have that working you then need to download go, and then download mingw, which is a suite of *nix utilities for windows. once you have that you need to run the bash shell, then go into where you downloaded this and then run `./build.sh dev` to build a development binary. you may then edit the configs and point them to the redis and cassandra servers you set up previously, and then edit any other options in the config you would like to modify. you are then the first person to run juxtaposition on windows without running redis externally

**Comment by ThatNerdyPikachu** [comment]
@superwhiskers redis for windows binaries do exist however...

**Comment by superwhiskers** [comment]
@ThatNerdyPikachu yes, but they're not new enough to work

**Comment by ThatNerdyPikachu** [comment]
@superwhiskers close this issue?
